title: Super Auto Pets Overview - Unofficial Website
description: This site aims to give a brief overview over the pets and mechanics in the game Super Auto Pets by teamwoodgames. Take a look!
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: M3IY0U
github1_username: M3IY0U
github2_username: sleightlyclueless
github1: https://github.com/M3IY0U
github2: https://github.com/sleightlyclueless
github: https://github.com/M3IY0U/SAPO
mail: contact@superautopets.com